# Generated by Django 4.1.3 on 2022-11-09 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2323232)),
                ('photo', models.ImageField(upload_to='')),
                ('scored', models.IntegerField()),
                ('missed', models.IntegerField()),
                ('game', models.IntegerField()),
                ('scores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23232)),
                ('date_birth', models.DateField()),
                ('description', models.CharField(max_length=10000)),
                ('last_name', models.CharField(max_length=23232)),
                ('played_minutes', models.IntegerField()),
                ('sub_off', models.IntegerField()),
                ('games', models.IntegerField()),
                ('number', models.IntegerField()),
                ('status', models.SmallIntegerField(choices=[(1, 'attacker'), (2, 'midfielder'), (3, 'defender'), (4, 'goalkeeper'), (6, 'substitute')], default=6)),
                ('captain', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23232)),
                ('photo', models.ImageField(max_length=23232, upload_to='')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=23232)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst', models.URLField()),
                ('yt', models.URLField()),
                ('tt', models.URLField()),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=344343)),
            ],
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=2323)),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=65676876)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminka.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turnir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=23232)),
                ('club', models.ManyToManyField(to='adminka.club')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('club_1_result', models.IntegerField()),
                ('club_2_result', models.IntegerField()),
                ('club1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffffff', to='adminka.club')),
                ('club2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsds', to='adminka.club')),
                ('turnir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminka.turnir')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='players',
            field=models.ManyToManyField(to='adminka.player'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminka.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
